[package]
name = "movie_comment_analyser"
version = "0.1.0"
edition = "2024"

[dependencies]
strsim = "0.11.1"
fancy-regex = "0.14.0"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
